services:
  next-template:
    image: next-template
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - path: ./.env
        required: true
    ports:
      - "${PORT}:${PORT}"
